CREATE TABLE REGIONS( 
	region_id int NOT NULL, 
	region_name VARCHAR(25) 
);

ALTER TABLE REGIONS
ADD CONSTRAINT reg_id_pk PRIMARY KEY (region_id);

 CREATE TABLE COUNTRIES( 
 	COUNTRY_ID CHAR(2) NOT NULL, 
	COUNTRY_NAME VARCHAR(40), 
	REGION_ID int, 
	CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID) 
); 

ALTER TABLE COUNTRIES
ADD  CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);
CREATE TABLE LOCATIONS( 
	LOCATION_ID int not null, 
	STREET_ADDRESS VARCHAR(40), 
	POSTAL_CODE VARCHAR(12), 
	CITY VARCHAR(30) NOT NULL, 
	STATE_PROVINCE VARCHAR(25), 
	COUNTRY_ID CHAR(2)
);
ALTER TABLE LOCATIONS	
ADD CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID),
add CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);


